version: '3.8' # Docker Compose version

services:
  p5js-app:
    build: .
    ports:
      - "8080:8080" # Map container's port 8080 to host's port 8080
    volumes:
      - .:/usr/src/app # Mount your project directory for live editing
    stdin_open: true   # Keep the container open
    tty: true          # Allocate a pseudo-TTY